; PlatformIO Project Configuration File for Pocket-Dongle-S3 16MB Flash/8MB PSRAM

[platformio]
src_dir = .
default_envs = Pocket-Dongle-S3

[keyboardlayouts]
build_flags = 
	-D LOCALE_win_en_GB

[core]
framework = arduino
extra_scripts = pre:extra_scripts.py
build_src_filter = 
	+<*>
	-<.git/>
	-<.svn/>
	-<test/>
	-<ui/>
build_unflags = 
	-DARDUINO_USB_MODE=1
	-std=gnu++11
	-std=gnu++14
	-std=gnu++17
build_flags = 
	${keyboardlayouts.build_flags}
	-std=gnu++2a
	-DARDUINO_USB_MODE=0
	-DARDUINO_USB_CDC_ON_BOOT=1
	-Wnarrowing
	-Wno-deprecated
	-Wwrite-strings
	-Wreturn-type
	-Wl,-z,muldefs
	-D CFG_TUD_ENABLED
lib_deps_core = 
	https://github.com/i-am-shodan/DuckScriptInterpreter#23aa3ba87e95f402ccab53beb9ead54602643dd7
	bblanchon/ArduinoJson@^7.0.3
	ivanseidel/LinkedList@0.0.0-alpha+sha.dac3874d28
	https://github.com/i-am-shodan/Uptime-Library

[core-esp32]
extends = core
platform = https://github.com/platformio/platform-espressif32.git
platform_packages = 
	platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.5
	platformio/framework-arduinoespressif32-libs @ https://github.com/espressif/esp32-arduino-libs.git#idf-release/v5.1
monitor_filters = esp32_exception_decoder
monitor_speed = 115200
build_flags = 
	${core.build_flags}
	-D LOLIN_WIFI_FIX
	-D DISABLE_STATUS_LED
	-D ENABLE_NONSERIAL_COMMAND_EXECUTION
	-D CFG_TUD_NCM
	-D CFG_TUD_ENABLED
	-D MIN_HEAP_SIZE=8192
	-D CONFIG_ASYNC_TCP_RUNNING_CORE=1
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-D WS_MAX_QUEUED_MESSAGES=64
	-D CONFIG_ASYNC_TCP_MAX_ACK_TIME=3000
	-D CONFIG_RESTART_DEBUG_STACK_DEPTH=14
	-Wl,--wrap=esp_panic_handler
lib_deps = 
	${core.lib_deps_core}
	https://github.com/mathieucarbou/AsyncTCPSock/archive/refs/tags/v1.0.3-dev.zip
	https://github.com/i-am-shodan/Adafruit_TinyUSB_Arduino#migrateTo334
	ESPAsyncWebServer=https://github.com/i-am-shodan/ESPAsyncWebServer
	ayushsharma82/ElegantOTA@3.1.0
	https://github.com/b5i/backtrace-saver-esp32#main

[core-esp32-s3]
extends = core-esp32
build_flags = 
	${core-esp32.build_flags}
	-D ARDUINO_ARCH_ESP32S3
	-D GENERIC_ESP32
	-D CONFIG_ASYNC_TCP_QUEUE_SIZE=128
	-D RX_PIN=44
	-D TX_PIN=43
lib_deps = 
    ${core-esp32.lib_deps}
	h2zero/NimBLE-Arduino@^1.4.2
	mathertel/OneButton
	lovyan03/LovyanGFX@^1.1.16

[env:Pocket-Dongle-S3]
extends = core-esp32-s3
;;;; FORCE PLATFORMIO TO USE LOCAL HARDWARE PROFILE DIRECTLY ;;;;
board = custom_s3_16mb_opi
board_build.partitions = default_16MB.csv
build_flags = 
	${core-esp32-s3.build_flags}
	-D POCKET_DONGLE_S3
	-D BOARD_HAS_PSRAM
	-D CONFIG_SPIRAM_MODE_OCT=1
	-mfix-esp32-psram-cache-issue
	-D HAS_SD
	-D USE_SD_INTERFACE
	-D NO_MIC
	-D NO_TOUCH
	-D NO_IR
	-D NO_LED
;;;;;;;; Reverted Stock Pin Config for TFT ;;;;;;;;
	-D DISPLAY_RST=14
	-D DISPLAY_DC=13
	-D DISPLAY_MOSI=11
	-D DISPLAY_CS=12
	-D DISPLAY_SCLK=10
	-D DISPLAY_MISO=-1
	-D DISPLAY_BUSY=-1
	-D DISPLAY_WIDTH=160
	-D DISPLAY_HEIGHT=80
	-D TFT_WIDTH=80
	-D TFT_HEIGHT=160
	-D DISPLAY_LEDA=-1
;;;;;;;; Reverted Stock Pin Config for SD ;;;;;;;;
	-D SD_SCLK_PIN=17
	-D SD_MOSI_PIN=18
	-D SD_MISO_PIN=16
	-D SD_CS_PIN=47
;;;;;;;; Reverted Stock Pin Config for Button ;;;;;;;;
	-D BTN_PIN=0
lib_deps = 
    ${core-esp32-s3.lib_deps}
	https://github.com/pololu/apa102-arduino